### PR TITLE
Change Fullscreen mode to Borderless Fullscreen

### PR DESCRIPTION
**Pull request by DrCox85**
It's change the Fullscreen faster and with Window on top.
Btw this is my solution, while on my PC the Fullscreen switch take 2 seconds to switch. And when mousecklick outside the Editor minimized,

### CODE REVIEW

**Comment by engor** [comment]
And now it shitches immediatelly?

**Comment by engor** [comment]
Thanks for PR!
One note - please try to use our code styling working on it to have more consistent code base.
For example, we don't use brackets in If statement: just `If _sullscreen`,
and parameters brackets have spaces on the edges but not between params: `CallFunc( 1,2 )`.
:)

**Comment by engor** [comment]
@DrCox85 
I see this code line: `If(Maximized)Then Restore()` but switching works w/o it.
Is it important? What a reason to use it?

**Comment by DrCox85** [comment]
1. on my PC it's switch immediatelly. What about your
2. ok next time i will care the code style, thanks for the hint
3. Switch the Window manually to maximize it's no more over on top when i switch to Fullscreen and then, when switch back then border was gone outside the Monitor. This is the only fix i found. 
`If(Maximized)Then Restore()`  it's important to me.

**Comment by engor** [comment]
1. On my PC both variants works fast.
3. Will try again to see it.

**Pull request merged**
