### PR TITLE
Added WIP code map

### PR DESCRIPTION
**Pull request by Hezkore**
I've added a code map view, it's far from perfect, but it sorta works.

Known issues are:
Jittering when scrolling large documents
Odd behaviour when Word Wrap is enabled

I was hoping for some help with the Word Wrap oddness.

### CODE REVIEW

**Comment by Hezkore** [comment]
Here's a video of how the code map looks and acts (word wrap issue not seen here): [https://youtu.be/TuM-VWJCYbo](https://youtu.be/TuM-VWJCYbo)

**Comment by engor** [comment]
`Jittering when scrolling large documents`
I fixed that by replacing ContentView.Offset with canvas.Translate.

> Odd behaviour when Word Wrap is enabled
I can't fix that too. 
Word wrap use not self measured width but width set by parent.
So if we set width=500, but inside of parent use width 200 (parent.AddView( this,"right",200)) then we'll see wrap by 200 not 500.

**Comment by engor** [comment]
WordWrap is fixed now! _Dirty hack while Mark have no time to changing mojox._

**Comment by Hezkore** [comment]
Good work cleaning this up!
Can't wait to test it once I get back home :)

**Pull request merged**
